import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import style from "./globals.module.css";
import Header from "./common/header";
import Footer from "./common/footer";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "next-portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({children} : {children: ReactNode}){
  return (
    <html>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
